app:
  extends:
    file: ./docker-compose.yml
    service: node
  command: node node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.config.test.js --port 80 --host 0.0.0.0

hub:
  image: selenium/hub:2.48.2

chrome:
  image: selenium/node-chrome:2.48.2
  links:
    - hub
    - app

firefox:
  image: selenium/node-firefox:2.48.2
  links:
    - hub
    - app

chromedebug:
  image: selenium/node-chrome-debug:2.48.2
  links:
    - hub
    - app
  ports:
    - 5900:5900

firefoxdebug:
  image: selenium/node-firefox-debug:2.48.2
  links:
    - hub
    - app
  ports:
    - 5901:5900

test:
  extends:
    file: ./docker-compose.yml
    service: node
  links:
    - hub
  environment:
    NODE_ENV: test
  command: node_modules/mocha/bin/mocha --config test/e2e/mocha.opts test/e2e test/e2e/test/*.js
